### ISSUE TITLE
EditorLayout.SearchTextField() method NullReferenceException

### ISSUE THREAD

**Issue by lightjiao** [sschmid/DesperateDevs#2]
**Describe the bug**
`EditorLayout.SearchTextField()`  method has code like below:
```
if (GUILayout.Button(string.Empty, GUI.skin.FindStyle("ToolbarSeachCancelButton")))
```

but there is no  *.guiskin file, `GUI.skin.FindStyle("ToolbarSeachCancelButton")` will return null, then cause NullReferenceException
```
NullReferenceException: Object reference not set to an instance of an object
UnityEngine.GUILayoutUtility.DoGetRect (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at <82a3a4e0a0a94de5afddd345f6cf50d1>:0)
UnityEngine.GUILayoutUtility.GetRect (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at <82a3a4e0a0a94de5afddd345f6cf50d1>:0)
UnityEngine.GUILayout.DoTextField (System.String text, System.Int32 maxLength, System.Boolean multiline, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at <82a3a4e0a0a94de5afddd345f6cf50d1>:0)
UnityEngine.GUILayout.TextField (System.String text, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at <82a3a4e0a0a94de5afddd345f6cf50d1>:0)
```

I use [Entitas.Generic](https://github.com/yosadchyi/Entitas.Generic) instead code generator ( more conviance with little performance price )
I don't find any *.guiskin in source code, can you help me to solve the problem?

*Unity Version: 2022.3.4f1 and 2021.3.28f1

**Comment by lightjiao** [comment]
Unity 2021.3.5 don't have this problem, It seems that Unity API is not compatible

**Comment by sschmid** [comment]
@lightjiao See this issue for and updated dll that fixes this:
https://github.com/sschmid/Entitas/issues/1067#issuecomment-1623734894

**Comment by sschmid** [comment]
I just checked the Entitas repo you linked and it hasn't been updated in many years. Please try the dll I linked in the issue, but there's a chance it's not compatible anymore because the repo is so old.

Alternatively, try using Unity Version 2022.3.2f1. I think Unity introduced this breaking change in 2022.3.3 or 2022.3.4

**Comment by sschmid** [comment]
If it doesn't work, I can try to provide a fixed version of the old DesperateDevs dll for you

**Comment by lightjiao** [comment]
It solve my problem perfectly, thanks a lot.

by the way,  the [Entitas.Generic](https://github.com/yosadchyi/Entitas.Generic) repo only use the core API of entitas, it is very simple and easy to use. I simplified it's API, looks good for me.

**Comment by JesseTG** [comment]
Could you put out a new release of this repo that includes the fix?
